### PR TITLE
add test for stripping of _pjax in url with multiple parameters

### PR DESCRIPTION
**Pull request by koenpunt**
This is a new version of #76

### CODE REVIEW

**Comment by khustochka** [comment]
That's exactly what I was looking for. In the current master `strip_pjax_param` does not work correctly in _pjax key is the last one in the query string, it leaves the trailng `&`.

**Comment by markets** [comment]
Hi @route @koenpunt 👋 

I'm upgrading a Rails app from 4 to 6, and when using the latest version of this gem v0.5.0, I can reproduce this "error"... I think we should reopen this issue.

**Comment by markets** [comment]
oh! thanks for reopening @route! 

@koenpunt could you please rebase with current master? Would be amazing to ship this fix :ok_hand: 

Thanks in advance!

**Comment by markets** [comment]
Thank you a lot @koenpunt for updating the branch! 👍 

@route could you please take a look?

**Comment by AlexLarra** [comment]
Thanks @koenpunt . Waiting anxious

**Comment by route** [comment]
I see no reason how this test passes after this commit in 2015 https://github.com/rails/rails/commit/394b7be0368cdf992b29c40bf7f501418d630b64

**Comment by route** [comment]
I picked up your branch and created a new PR. Thanks everyone!

**Comment by route** [comment]
Just pushed to rubygems

**Comment by markets** [comment]
Thanks @route 👏

**Pull request closed without merging**
